### ISSUE TITLE
no log no bank:(

### ISSUE THREAD

**Issue by Owain94** [T7x/Logger-rs#1]

**Comment by T7x** [comment]
No hate pls :sob: 

> https://i.imgur.com/8bvFJJm.png
> 
> thanks for the gmail accounts ez clear see ya later

**Comment by T7x** [comment]
I wil remove it tomorrow and only leave one for some cw tards

**Comment by T7x** [comment]
Removed most plugins exept the Castlewars plugin if that is fine, Sorry for making this worse as it should've been
